name: Release
run-name: Release (${{ inputs.version }})

on:
  workflow_dispatch:
    inputs:
      is-release:
        description: Publish release
        required: true
        type: boolean
      version:
        description: Pack version (e.g. 1.3.1+1.21)
        required: true
        type: string

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare deploy info
        id: deploy-info
        shell: bash
        run: |
          PACK_NAME=$(jq -r '.name' project.json)
          NO_SPACE_NAME=$(echo "$PACK_NAME" | tr -d ' ')
          VERSION="${{ inputs.version }}"

          echo "version-slug=v$VERSION" >> $GITHUB_OUTPUT
          echo "release-name=$PACK_NAME v$VERSION" >> $GITHUB_OUTPUT
          echo "artifact-file=$NO_SPACE_NAME-v$VERSION.zip" >> $GITHUB_OUTPUT
          echo "modrinth-project-id=$(jq -r '.["modrinth-id"]' project.json)" >> $GITHUB_OUTPUT

      - name: Parse changelog
        id: changelog
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: v${{ inputs.version }}
          changelog: CHANGELOG.md

      - name: Build resourcepack or datapack
        working-directory: pack
        shell: bash
        run: |
          zip -r "${{ steps.deploy-info.outputs.artifact-file }}" *
          mv "${{ steps.deploy-info.outputs.artifact-file }}" "${{ github.workspace }}"

      - name: Create GitHub release
        if: inputs.is-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.deploy-info.outputs.version-slug }}
          name: ${{ steps.deploy-info.outputs.release-name }}
          body: ${{ steps.changelog.outputs.release-notes }}
          files: |
            ${{ steps.deploy-info.outputs.artifact-file }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Modrinth Release
        if: inputs.is-release
        id: modrinth-release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ steps.deploy-info.outputs.release-name }}
          version: ${{ steps.deploy-info.outputs.version-slug }}
          changelog: ${{ steps.changelog.outputs.release-notes }}
          loaders: minecraft
          files: ${{ steps.deploy-info.outputs.artifact-file }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Update Modrinth decription
        if: inputs.is-release
        uses: funnyboy-roks/modrinth-auto-desc@v1.7
        with:
          auth-token: ${{ secrets.MODRINTH_TOKEN }}
          slug: ${{ steps.deploy-info.outputs.modrinth-project-id }}
          readme: MODRINTH.md

      - name: Post release to Discord
        if: inputs.is-release
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ${{ steps.deploy-info.outputs.release-name }} has been released! https://modrinth.com/mod/${{ steps.deploy-info.outputs.modrinth-project-id }}/version/${{ steps.deploy-info.outputs.version-slug }}
